import { type NextPage } from "next";
import Head from "next/head";
import About from "~/sections/About";
import Hero from "~/sections/Hero";
import { Navbar } from "~/sections/Navbar";
import Skills from "~/sections/Skills";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kasper Luna</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <About />
        <Skills />
      </main>
    </>
  );
};

export default Home;
